// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react";

// biome-ignore lint/suspicious/noExplicitAny: <explanation>
export const Index: Record<string, any> = {
	default: {
		"consent-solution": {
			name: "consent-solution",
			description: "",
			type: "registry:ui",
			registryDependencies: [],
			files: [
				{
					path: "node_modules/@koroflow/shadcn/src/themes/default/components/consent/cookie-banner.tsx",
					type: "registry:ui",
					target: "components/consent/cookie-banner.tsx",
				},
				{
					path: "node_modules/@koroflow/shadcn/src/themes/default/components/consent/overlay.tsx",
					type: "registry:ui",
					target: "components/consent/overlay.tsx",
				},
				{
					path: "node_modules/@koroflow/shadcn/src/themes/default/components/consent/consent-customization-dialog.tsx",
					type: "registry:ui",
					target: "components/consent/consent-customization-dialog.tsx",
				},
				{
					path: "node_modules/@koroflow/shadcn/src/themes/default/components/consent/consent-customization-widget.tsx",
					type: "registry:ui",
					target: "components/consent/consent-customization-widget.tsx",
				},
			],
			categories: undefined,
			component: React.lazy(
				() => import("@koroflow/shadcn/themes/default/components/consent/cookie-banner"),
			),
			source: "",
			meta: undefined,
		},
		utils: {
			name: "utils",
			description: "",
			type: "registry:lib",
			registryDependencies: undefined,
			files: [
				{
					path: "node_modules/@koroflow/shadcn/src/themes/default/lib/utils.ts",
					type: "registry:lib",
					target: "",
				},
			],
			categories: undefined,
			component: React.lazy(() => import("@koroflow/shadcn/themes/default/lib/utils")),
			source: "",
			meta: undefined,
		},
		"consent-solution-demo": {
			name: "consent-solution-demo",
			description: "",
			type: "registry:example",
			registryDependencies: ["consent-solution"],
			files: [
				{
					path: "node_modules/@koroflow/shadcn/src/themes/default/examples/consent-solution-demo.tsx",
					type: "registry:example",
					target: "",
				},
			],
			categories: undefined,
			component: React.lazy(
				() => import("@koroflow/shadcn/themes/default/examples/consent-solution-demo"),
			),
			source: "",
			meta: undefined,
		},
		"consent-solution-minimal-demo": {
			name: "consent-solution-minimal-demo",
			description: "",
			type: "registry:example",
			registryDependencies: ["consent-solution"],
			files: [
				{
					path: "node_modules/@koroflow/shadcn/src/themes/default/examples/consent-solution-minimal-demo.tsx",
					type: "registry:example",
					target: "",
				},
			],
			categories: undefined,
			component: React.lazy(
				() => import("@koroflow/shadcn/themes/default/examples/consent-solution-minimal-demo"),
			),
			source: "",
			meta: undefined,
		},
		"consent-solution-callback-demo": {
			name: "consent-solution-callback-demo",
			description: "",
			type: "registry:example",
			registryDependencies: ["consent-solution"],
			files: [
				{
					path: "node_modules/@koroflow/shadcn/src/themes/default/examples/consent-solution-callback-demo.tsx",
					type: "registry:example",
					target: "",
				},
			],
			categories: undefined,
			component: React.lazy(
				() => import("@koroflow/shadcn/themes/default/examples/consent-solution-callback-demo"),
			),
			source: "",
			meta: undefined,
		},
		"dev-tool-example": {
			name: "dev-tool-example",
			description: "",
			type: "registry:example",
			registryDependencies: ["consent-solution"],
			files: [
				{
					path: "node_modules/@koroflow/shadcn/src/themes/default/examples/dev-tool-example.tsx",
					type: "registry:example",
					target: "",
				},
			],
			categories: undefined,
			component: React.lazy(
				() => import("@koroflow/shadcn/themes/default/examples/dev-tool-example"),
			),
			source: "",
			meta: undefined,
		},
	},
};
